In [1]:
import numpy as np

In [26]:
def sigmoid(u):
    return 1 / (1 + np.exp(-u))

In [3]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(my_matrix)

[[1 2 3]
 [4 5 6]]


In [4]:
my_matrix.shape

(2, 3)

In [7]:
#primeira linha
my_matrix[0,:]

array([1, 2, 3])

In [9]:
#primeira coluna
my_matrix[:,0]

array([1, 4])

In [17]:
aluno_1 = [0,1,1,1,0,0]
aluno_2 = [0,1,1,1,0,0]
aluno_3 = [1,1,1,0,0,0]
aluno_4 = [0,1,1,0,0,1]
aluno_5 = [0,1,1,1,0,0]
aluno_6 = [1,0,0,0,1,1]
entradas = np.array([aluno_1, aluno_2, aluno_3, aluno_4, aluno_5, aluno_6])
entradas

array([[0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 1]])

In [18]:
entradas.shape[0]

6

In [19]:
#entradas = np.append(1, entradas)
entradas = np.c_[np.ones(entradas.shape[0]), entradas]
entradas

array([[ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  1.,  1.]])

In [20]:
entradas.shape

(6, 7)

In [23]:
pesos = np.array(
        [[0.0, 0.0, 0.0],
         [0.0, 0.1, 0.2],
         [0.0, 0.3, 0.4],
         [0.0, 0.5, 0.6],
         [0.0, 0.7, 0.8],
         [0.0, 0.9, 1.0],
         [0.0, 0.1, 0.2]])
pesos

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0.1,  0.2],
       [ 0. ,  0.3,  0.4],
       [ 0. ,  0.5,  0.6],
       [ 0. ,  0.7,  0.8],
       [ 0. ,  0.9,  1. ],
       [ 0. ,  0.1,  0.2]])

In [24]:
pesos.shape

(7, 3)

In [25]:
energia_ativacao_Uv = np.dot(entradas, pesos)
energia_ativacao_Uv

array([[ 0. ,  1.5,  1.8],
       [ 0. ,  1.5,  1.8],
       [ 0. ,  0.9,  1.2],
       [ 0. ,  0.9,  1.2],
       [ 0. ,  1.5,  1.8],
       [ 0. ,  1.1,  1.4]])

In [29]:
ativacao_gUv = sigmoid(energia_ativacao_Uv)
ativacao_gUv

array([[ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.7109495 ,  0.76852478],
       [ 0.5       ,  0.7109495 ,  0.76852478],
       [ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.75026011,  0.80218389]])

In [42]:
numeros_aleatorios = np.random.random((ativacao_gUv.shape[0], ativacao_gUv.shape[1]))
numeros_aleatorios

array([[ 0.970724  ,  0.34861729,  0.02220276],
       [ 0.74130219,  0.47102658,  0.95323701],
       [ 0.94982014,  0.10744772,  0.65851508],
       [ 0.11767529,  0.66836288,  0.04732326],
       [ 0.93548064,  0.00659542,  0.01786768],
       [ 0.09365678,  0.1904114 ,  0.85444333]])

In [44]:
probabilidade_associacao_neuronios = ativacao_gUv >= numeros_aleatorios
probabilidade_associacao_neuronios

array([[False,  True,  True],
       [False,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]], dtype=bool)

In [45]:
probabilidade_associacao_neuronios = np.array([[False, False, True],
                                               [False, True, True],
                                               [False, True, True],
                                               [True, True, True],
                                               [True, True, True],
                                               [True, True, True]])

In [46]:
probabilidade_associacao_neuronios

array([[False, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [49]:
energia_ativacao_Uh = np.dot(probabilidade_associacao_neuronios, pesos.T)
energia_ativacao_Uh

array([[ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  0.2],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3]])

In [50]:
ativacao_gUh = sigmoid(energia_ativacao_Uh)
ativacao_gUh

array([[ 0.5       ,  0.549834  ,  0.59868766,  0.64565631,  0.68997448,
         0.73105858,  0.549834  ],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252]])

In [51]:
ativacao_gUh[:,0]

array([ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [52]:
ativacao_gUh[:,0] = 1.0
ativacao_gUh

array([[ 1.        ,  0.549834  ,  0.59868766,  0.64565631,  0.68997448,
         0.73105858,  0.549834  ],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252]])

In [54]:
energia_ativacao_estimada_Uv = np.dot(ativacao_gUh, pesos)
energia_ativacao_estimada_Uv

array([[ 0.        ,  1.75333611,  2.12984061],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929]])

In [57]:
ativacao_estimada_gUv = sigmoid(energia_ativacao_estimada_Uv)
ativacao_estimada_gUv

array([[ 0.5       ,  0.85237309,  0.89376988],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508]])

In [59]:
#entrada e ativação da ida
associacao_positiva = np.dot(entradas.T, ativacao_gUv)
associacao_positiva

array([[ 3.        ,  4.62488254,  4.91368026],
       [ 1.        ,  1.46120961,  1.57070867],
       [ 2.5       ,  3.87462243,  4.11149637],
       [ 2.5       ,  3.87462243,  4.11149637],
       [ 1.5       ,  2.45272343,  2.57444681],
       [ 0.5       ,  0.75026011,  0.80218389],
       [ 1.        ,  1.46120961,  1.57070867]])

In [60]:
#entrada e ativação da volta
associacao_negativa = np.dot(ativacao_gUh.T, ativacao_estimada_gUv)
associacao_negativa

array([[ 3.        ,  5.27992467,  5.50424529],
       [ 1.71102329,  3.01203758,  3.13987817],
       [ 1.96981326,  3.46874108,  3.61575229],
       [ 2.19847842,  3.87215538,  4.03612393],
       [ 2.38892343,  4.20796885,  4.38608543],
       [ 2.5402581 ,  4.47462426,  4.66401163],
       [ 1.71102329,  3.01203758,  3.13987817]])