In [1]:
import numpy as np

In [2]:
def sigmoid(u):
    return 1 / (1 + np.exp(-u))

In [ ]:
def calcular_erro(entrada, entrada_reconstruida):

In [3]:
my_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(my_matrix)

[[1 2 3]
 [4 5 6]]


In [4]:
my_matrix.shape

(2, 3)

In [5]:
#primeira linha
my_matrix[0,:]

array([1, 2, 3])

In [6]:
#primeira coluna
my_matrix[:,0]

array([1, 4])

In [36]:
taxa_de_aprendizagem = 0.1

In [7]:
aluno_1 = [0,1,1,1,0,0]
aluno_2 = [0,1,1,1,0,0]
aluno_3 = [1,1,1,0,0,0]
aluno_4 = [0,1,1,0,0,1]
aluno_5 = [0,1,1,1,0,0]
aluno_6 = [1,0,0,0,1,1]
entradas = np.array([aluno_1, aluno_2, aluno_3, aluno_4, aluno_5, aluno_6])
entradas

array([[0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 1]])

In [8]:
entradas.shape[0]

6

In [9]:
#entradas = np.append(1, entradas)
entradas = np.c_[np.ones(entradas.shape[0]), entradas]
entradas

array([[ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  1.,  1.]])

In [10]:
entradas.shape

(6, 7)

In [11]:
pesos = np.array(
        [[0.0, 0.0, 0.0],
         [0.0, 0.1, 0.2],
         [0.0, 0.3, 0.4],
         [0.0, 0.5, 0.6],
         [0.0, 0.7, 0.8],
         [0.0, 0.9, 1.0],
         [0.0, 0.1, 0.2]])
pesos

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0.1,  0.2],
       [ 0. ,  0.3,  0.4],
       [ 0. ,  0.5,  0.6],
       [ 0. ,  0.7,  0.8],
       [ 0. ,  0.9,  1. ],
       [ 0. ,  0.1,  0.2]])

In [12]:
pesos.shape

(7, 3)

In [13]:
energia_ativacao_Uv = np.dot(entradas, pesos)
energia_ativacao_Uv

array([[ 0. ,  1.5,  1.8],
       [ 0. ,  1.5,  1.8],
       [ 0. ,  0.9,  1.2],
       [ 0. ,  0.9,  1.2],
       [ 0. ,  1.5,  1.8],
       [ 0. ,  1.1,  1.4]])

In [14]:
ativacao_gUv = sigmoid(energia_ativacao_Uv)
ativacao_gUv

array([[ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.7109495 ,  0.76852478],
       [ 0.5       ,  0.7109495 ,  0.76852478],
       [ 0.5       ,  0.81757448,  0.85814894],
       [ 0.5       ,  0.75026011,  0.80218389]])

In [15]:
numeros_aleatorios = np.random.random((ativacao_gUv.shape[0], ativacao_gUv.shape[1]))
numeros_aleatorios

array([[ 0.07891021,  0.34866721,  0.24276382],
       [ 0.59238227,  0.81209019,  0.65219141],
       [ 0.15108547,  0.32043873,  0.53414475],
       [ 0.02179819,  0.22749686,  0.78248417],
       [ 0.70124719,  0.22579753,  0.85562067],
       [ 0.90927114,  0.1731394 ,  0.46698919]])

In [16]:
probabilidade_associacao_neuronios = ativacao_gUv >= numeros_aleatorios
probabilidade_associacao_neuronios

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [17]:
probabilidade_associacao_neuronios = np.array([[False, False, True],
                                               [False, True, True],
                                               [False, True, True],
                                               [True, True, True],
                                               [True, True, True],
                                               [True, True, True]])

In [18]:
probabilidade_associacao_neuronios

array([[False, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [19]:
energia_ativacao_Uh = np.dot(probabilidade_associacao_neuronios, pesos.T)
energia_ativacao_Uh

array([[ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  0.2],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3],
       [ 0. ,  0.3,  0.7,  1.1,  1.5,  1.9,  0.3]])

In [27]:
entradas_reconstruidas = sigmoid(energia_ativacao_Uh)
entradas_reconstruidas

array([[ 0.5       ,  0.549834  ,  0.59868766,  0.64565631,  0.68997448,
         0.73105858,  0.549834  ],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 0.5       ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252]])

In [28]:
entradas_reconstruidas[:,0] = 1.0
entradas_reconstruidas

array([[ 1.        ,  0.549834  ,  0.59868766,  0.64565631,  0.68997448,
         0.73105858,  0.549834  ],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252],
       [ 1.        ,  0.57444252,  0.66818777,  0.75026011,  0.81757448,
         0.86989153,  0.57444252]])

In [29]:
energia_ativacao_estimada_Uv = np.dot(entradas_reconstruidas, pesos)
energia_ativacao_estimada_Uv

array([[ 0.        ,  1.75333611,  2.12984061],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929],
       [ 0.        ,  2.04567939,  2.47115929]])

In [23]:
ativacao_estimada_gUv = sigmoid(energia_ativacao_estimada_Uv)
ativacao_estimada_gUv

array([[ 0.5       ,  0.85237309,  0.89376988],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508],
       [ 0.5       ,  0.88551032,  0.92209508]])

In [24]:
#entrada e ativação da ida
associacao_positiva = np.dot(entradas.T, ativacao_gUv)
associacao_positiva

array([[ 3.        ,  4.62488254,  4.91368026],
       [ 1.        ,  1.46120961,  1.57070867],
       [ 2.5       ,  3.87462243,  4.11149637],
       [ 2.5       ,  3.87462243,  4.11149637],
       [ 1.5       ,  2.45272343,  2.57444681],
       [ 0.5       ,  0.75026011,  0.80218389],
       [ 1.        ,  1.46120961,  1.57070867]])

In [30]:
#entrada e ativação da volta
associacao_negativa = np.dot(entradas_reconstruidas.T, ativacao_estimada_gUv)
associacao_negativa

array([[ 3.        ,  5.27992467,  5.50424529],
       [ 1.71102329,  3.01203758,  3.13987817],
       [ 1.96981326,  3.46874108,  3.61575229],
       [ 2.19847842,  3.87215538,  4.03612393],
       [ 2.38892343,  4.20796885,  4.38608543],
       [ 2.5402581 ,  4.47462426,  4.66401163],
       [ 1.71102329,  3.01203758,  3.13987817]])

In [35]:
erro_epoca = np.sum(np.square(entradas - entradas_reconstruidas))
erro_epoca

11.040968380071609

In [37]:
pesos_proxima_epoca = pesos + taxa_de_aprendizagem * ((associacao_positiva - associacao_negativa) / entradas.shape[0])
pesos_proxima_epoca

array([[ 0.        , -0.01091737, -0.00984275],
       [-0.01185039,  0.07415287,  0.17384718],
       [ 0.00883645,  0.30676469,  0.4082624 ],
       [ 0.00502536,  0.50004112,  0.60125621],
       [-0.01481539,  0.67074591,  0.76980602],
       [-0.0340043 ,  0.83792726,  0.9356362 ],
       [-0.01185039,  0.07415287,  0.17384718]])

In [39]:
if pesos is None:
    print(pesos)

In [40]:
if pesos is not None:
    print(pesos)

[[ 0.   0.   0. ]
 [ 0.   0.1  0.2]
 [ 0.   0.3  0.4]
 [ 0.   0.5  0.6]
 [ 0.   0.7  0.8]
 [ 0.   0.9  1. ]
 [ 0.   0.1  0.2]]
