In [23]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
import pandas

In [14]:
fertility_df = pandas.read_csv('fertility_Diagnosis.txt', header=-1)
labels = ['Season','Age','Childish diseases','Accident or serious trauma','Surgical intervention',
          'High fevers in the last year','Frequency of alcohol consumption','Smoking habit',
          'Number of hours spent sitting per day ene-16','Output']
fertility_df.columns = labels
fertility_df['Output'] = fertility_df['Output'].map({'N': 0, 'O': 1}).astype(int)
fertility_df

Season   Age  Childish diseases  Accident or serious trauma  \
0    -0.33  0.69                  0                           1   
1    -0.33  0.94                  1                           0   
2    -0.33  0.50                  1                           0   
3    -0.33  0.75                  0                           1   
4    -0.33  0.67                  1                           1   
5    -0.33  0.67                  1                           0   
6    -0.33  0.67                  0                           0   
7    -0.33  1.00                  1                           1   
8     1.00  0.64                  0                           0   
9     1.00  0.61                  1                           0   
10    1.00  0.67                  1                           1   
11    1.00  0.78                  1                           1   
12    1.00  0.75                  1                           1   
13    1.00  0.81                  1                           0   
14    1.00  0.94                  1                           1   
15    1.00  0.81                  1                           1   
16    1.00  0.64                  1                           0   
17    1.00  0.69                  1                           0   
18    1.00  0.75                  1                           1   
19    1.00  0.67                  1                           0   
20    1.00  0.67                  0                           0   
21    1.00  0.75                  1                           0   
22    1.00  0.67                  1                           1   
23    1.00  0.69                  1                           0   
24    1.00  0.56                  1                           0   
25    1.00  0.67                  1                           0   
26    1.00  0.67                  1                           0   
27    1.00  0.78                  1                           1   
28    1.00  0.58                  0                           0   
29    1.00  0.67                  0                           0   
..     ...   ...                ...                         ...   
70   -0.33  0.50                  1                           1   
71    0.33  0.69                  1                           0   
72    1.00  0.56                  1                           0   
73   -1.00  0.50                  1                           0   
74   -1.00  0.53                  1                           0   
75   -1.00  0.78                  1                           0   
76   -1.00  0.75                  1                           0   
77   -1.00  0.72                  1                           1   
78   -1.00  0.53                  1                           1   
79   -1.00  1.00                  1                           0   
80   -0.33  0.92                  1                           1   
81   -1.00  0.81                  1                           1   
82   -0.33  0.92                  1                           0   
83   -0.33  0.86                  1                           1   
84   -0.33  0.78                  1                           0   
85   -0.33  0.89                  1                           1   
86   -0.33  0.75                  1                           1   
87   -0.33  0.75                  1                           1   
88   -0.33  0.83                  1                           1   
89   -0.33  0.81                  1                           1   
90   -0.33  0.81                  1                           1   
91    0.33  0.78                  1                           0   
92    0.33  0.75                  1                           1   
93    0.33  0.75                  1                           0   
94    1.00  0.58                  1                           0   
95   -1.00  0.67                  1                           0   
96   -1.00  0.61                  1                           0   
97   -1.00  0.67                  1                

In [15]:
training_data, test_data, training_output, test_output = train_test_split(fertility_df, fertility_df['Output'], test_size=0.3)
del training_data['Output']
del test_data['Output']

In [16]:
def normalize_features(feature_matrix):
    norms = np.linalg.norm(feature_matrix, axis=0)
    return feature_matrix / norms, norms

In [17]:
normalized_training_data, norms = normalize_features(training_data)

In [18]:
normalized_training_data

Season       Age  Childish diseases  Accident or serious trauma  \
44 -0.147538  0.093719           0.131306                    0.182574   
56 -0.048687  0.093719           0.131306                    0.182574   
48 -0.048687  0.113170           0.131306                    0.182574   
89 -0.048687  0.143231           0.131306                    0.182574   
22  0.147538  0.118475           0.131306                    0.182574   
73 -0.147538  0.088414           0.131306                    0.000000   
3  -0.048687  0.132621           0.000000                    0.182574   
71  0.048687  0.122011           0.131306                    0.000000   
29  0.147538  0.118475           0.000000                    0.000000   
49 -0.048687  0.132621           0.131306                    0.182574   
8   0.147538  0.113170           0.000000                    0.000000   
58 -0.048687  0.099024           0.131306                    0.182574   
15  0.147538  0.143231           0.131306                    0.182574   
35 -0.147538  0.137926           0.131306                    0.182574   
65 -0.048687  0.099024           0.000000                    0.000000   
77 -0.147538  0.127316           0.131306                    0.182574   
60  0.147538  0.099024           0.000000                    0.000000   
93  0.048687  0.132621           0.131306                    0.000000   
17  0.147538  0.122011           0.131306                    0.000000   
16  0.147538  0.113170           0.131306                    0.000000   
47 -0.048687  0.127316           0.131306                    0.182574   
34  0.147538  0.099024           0.131306                    0.182574   
52 -0.048687  0.093719           0.131306                    0.182574   
2  -0.048687  0.088414           0.131306                    0.000000   
55 -0.048687  0.102560           0.131306                    0.000000   
38 -0.147538  0.118475           0.000000                    0.000000   
37 -0.147538  0.099024           0.131306                    0.000000   
57 -0.048687  0.122011           0.131306                    0.182574   
30  0.147538  0.107865           0.131306                    0.000000   
50 -0.048687  0.118475           0.131306                    0.000000   
..       ...       ...                ...                         ...   
97 -0.147538  0.118475           0.131306                    0.182574   
0  -0.048687  0.122011           0.000000                    0.182574   
28  0.147538  0.102560           0.000000                    0.000000   
13  0.147538  0.143231           0.131306                    0.000000   
23  0.147538  0.122011           0.131306                    0.000000   
96 -0.147538  0.107865           0.131306                    0.000000   
43 -0.147538  0.099024           0.131306                    0.000000   
75 -0.147538  0.137926           0.131306                    0.000000   
42 -0.147538  0.102560           0.131306                    0.000000   
24  0.147538  0.099024           0.131306                    0.000000   
40 -0.147538  0.093719           0.131306                    0.182574   
7  -0.048687  0.176828           0.131306                    0.182574   
88 -0.048687  0.146767           0.131306                    0.182574   
68 -0.048687  0.088414           0.131306                    0.000000   
98 -0.147538  0.113170           0.131306                    0.000000   
36 -0.147538  0.137926           0.131306                    0.000000   
95 -0.147538  0.118475           0.131306                    0.000000   
62 -0.147538  0.107865           0.131306                    0.182574   
20  0.147538  0.118475           0.000000                    0.000000   
63 -0.147538  0.099024           0.131306                    0.000000   
11  0.147538  0.137926           0.131306                    0.182574   
90 -0.048687  0.143231           0.131306                    0.182574   
86 -0.048687  0.132621           0.131306                    0.1

In [22]:
normalized_training_data.mean(axis=0)

Season                                         -0.022320
Age                                             0.117793
Childish diseases                               0.108797
Accident or serious trauma                      0.078246
Surgical intervention                           0.093678
High fevers in the last year                    0.037143
Frequency of alcohol consumption                0.117262
Smoking habit                                  -0.054011
Number of hours spent sitting per day ene-16    0.109472
dtype: float64

In [21]:
normalized_training_data.std(axis=0)

Season                                          0.118268
Age                                             0.020410
Childish diseases                               0.049844
Accident or serious trauma                      0.091003
Surgical intervention                           0.074767
High fevers in the last year                    0.114425
Frequency of alcohol consumption                0.023303
Smoking habit                                   0.107393
Number of hours spent sitting per day ene-16    0.048321
dtype: float64

In [24]:
scaled_training_data = preprocessing.scale(training_data)

In [26]:
scaled_training_data.mean(axis=0)

array([  3.17206578e-17,   6.81994144e-17,  -1.07850237e-16,
        -3.17206578e-18,  -1.14194368e-16,  -1.66533454e-17,
         6.15380762e-16,  -6.02692499e-17,   1.39570895e-16])

In [27]:
scaled_training_data.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [28]:
normalized_training_data = preprocessing.normalize(training_data)

In [29]:
normalized_training_data.mean(axis=0)

array([-0.06372877,  0.30275861,  0.37046235,  0.18653246,  0.27140812,
        0.08219438,  0.37123681, -0.16934525,  0.19083647])

In [30]:
normalized_training_data.std(axis=0)

array([ 0.36084317,  0.05280054,  0.17452312,  0.21738913,  0.21843362,
        0.25041942,  0.07407596,  0.33782803,  0.09031904])

In [7]:
clf = MLPClassifier(alpha=1e-5)
clf.fit(training_data, training_output)
print(clf)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)


/media/discoD/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


In [8]:
clf.get_params()

{'activation': 'relu',
 'alpha': 1e-05,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_iter': 200,
 'momentum': 0.9,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

In [9]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70 entries, 90 to 84
Data columns (total 9 columns):
Season                                          70 non-null float64
Age                                             70 non-null float64
Childish diseases                               70 non-null int64
Accident or serious trauma                      70 non-null int64
Surgical intervention                           70 non-null int64
High fevers in the last year                    70 non-null int64
Frequency of alcohol consumption                70 non-null float64
Smoking habit                                   70 non-null int64
Number of hours spent sitting per day ene-16    70 non-null float64
dtypes: float64(4), int64(5)
memory usage: 5.5 KB


In [11]:
training_output.describe()

count    70.000000
mean      0.128571
std       0.337142
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000
Name: Output, dtype: float64

In [12]:
test_output.describe()

count    30.000000
mean      0.100000
std       0.305129
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000
Name: Output, dtype: float64